name: Release Build

on:
  push:
    tags:
      - "v*" # Триггер на теги, начинающиеся с 'v'

permissions:
  contents: write # Разрешение на создание релизов

jobs:
  build:
    name: Build Release
    runs-on: self-hosted
    strategy:
      matrix:
        include:
          - os: windows
            arch: amd64
            ext: .exe
          - os: darwin
            arch: amd64
            ext: ""
          - os: darwin
            arch: arm64
            ext: ""
          - os: linux
            arch: amd64
            ext: ""
          - os: linux
            arch: arm64
            ext: ""

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24.2"
          cache: true

      - name: Get version
        id: get_version
        shell: bash
        run: |
          echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          go install github.com/josephspurrier/goversioninfo/cmd/goversioninfo@latest
          go install github.com/akavel/rsrc@latest

      - name: Generate Windows resources
        if: matrix.os == 'windows'
        run: |
          # Обновляем версию в файле
          sed -i "s/\"ProductVersion\": \".*\"/\"ProductVersion\": \"$VERSION\"/" assets/versioninfo.json
          sed -i "s/\"FileVersion\": \"\"/\"FileVersion\": \"$VERSION\"/" assets/versioninfo.json

          # Генерируем .syso файл
          goversioninfo -platform-specific=true -manifest=assets/excel-cleaner.manifest -icon=assets/icon.ico -o=resource_windows_amd64.syso assets/versioninfo.json

      - name: Build
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
          VERSION: ${{ steps.get_version.outputs.VERSION }}
        run: |
          if [ "${{ matrix.os }}" = "darwin" ]; then
            go build -v -ldflags="-X 'main.Version=${VERSION}'" -o "excel-cleaner${{ matrix.ext }}"
            # Создаем .app bundle для macOS
            mkdir -p Excel\ Cleaner.app/Contents/MacOS
            mkdir -p Excel\ Cleaner.app/Contents/Resources
            cp excel-cleaner Excel\ Cleaner.app/Contents/MacOS/
            cp assets/icon.icns Excel\ Cleaner.app/Contents/Resources/
            cp assets/Info.plist Excel\ Cleaner.app/Contents/
            zip -r "excel-cleaner-${{ steps.get_version.outputs.VERSION }}-${{ matrix.os }}-${{ matrix.arch }}.zip" Excel\ Cleaner.app README.md LICENSE
          else
            go build -v -ldflags="-X 'main.Version=${VERSION}'" -o "excel-cleaner${{ matrix.ext }}"
            zip "excel-cleaner-${{ steps.get_version.outputs.VERSION }}-${{ matrix.os }}-${{ matrix.arch }}.zip" "excel-cleaner${{ matrix.ext }}" README.md LICENSE
          fi

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: excel-cleaner-${{ matrix.os }}-${{ matrix.arch }}
          path: excel-cleaner-${{ steps.get_version.outputs.VERSION }}-${{ matrix.os }}-${{ matrix.arch }}.zip
          retention-days: 1
          compression-level: 0

  create-release:
    name: Create Release
    needs: build
    runs-on: self-hosted
    permissions:
      contents: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          merge-multiple: true

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/excel-cleaner-*.zip
          draft: false
          prerelease: false
          generate_release_notes: true
